## Fake News Classifier Using LSTM
#### dataset :- https://www.kaggle.com/datasets/saurabhshahane/fake-news-classification

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('Dataset.csv')
df.shape

(72134, 4)

In [3]:
df.head()

Unnamed: 0                                              title  \
0           0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...   
1           1                                                NaN   
2           2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
3           3  Bobby Jindal, raised Hindu, uses story of Chri...   
4           4  SATAN 2: Russia unvelis an image of its terrif...   

                                                text  label  
0  No comment is expected from Barack Obama Membe...      1  
1     Did they post their votes for Hillary already?      1  
2   Now, most of the demonstrators gathered last ...      1  
3  A dozen politically active pastors came here f...      0  
4  The RS-28 Sarmat missile, dubbed Satan 2, will...      1

In [4]:
df.isnull().sum()

Unnamed: 0      0
title         558
text           39
label           0
dtype: int64

In [5]:
df=df.dropna()

In [6]:
df.head()

Unnamed: 0                                              title  \
0           0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...   
2           2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
3           3  Bobby Jindal, raised Hindu, uses story of Chri...   
4           4  SATAN 2: Russia unvelis an image of its terrif...   
5           5  About Time! Christian Group Sues Amazon and SP...   

                                                text  label  
0  No comment is expected from Barack Obama Membe...      1  
2   Now, most of the demonstrators gathered last ...      1  
3  A dozen politically active pastors came here f...      0  
4  The RS-28 Sarmat missile, dubbed Satan 2, will...      1  
5  All we can say on this one is it s about time ...      1

In [7]:
## Get the Independent Features

X=df.drop('label',axis=1)

In [8]:
## Get the Dependent features
y=df['label']

In [9]:
X.shape

(71537, 3)

In [10]:
y.shape

(71537,)

In [11]:
import tensorflow as tf

In [12]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

# One Hot Encoding

In [13]:
### Vocabulary size
voc_size=5000

In [14]:
messages=X.copy()

In [15]:
messages['title'].iloc[1]

'UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MOST CHARLOTTE RIOTERS WERE “PEACEFUL” PROTESTERS…In Her Home State Of North Carolina [VIDEO]'

In [16]:
messages.reset_index(inplace=True)

In [17]:
import nltk
import re
from nltk.corpus import stopwords

In [18]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\supra\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [19]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [20]:
corpus

['law enforc high alert follow threat cop white blacklivesmatt fyf terrorist video',
 'unbeliev obama attorney gener say charlott rioter peac protest home state north carolina video',
 'bobbi jindal rais hindu use stori christian convers woo evangel potenti bid',
 'satan russia unv imag terrifi new supernuk western world take notic',
 'time christian group sue amazon splc design hate group',
 'dr ben carson target ir never audit spoke nation prayer breakfast',
 'hous intel chair trump russia fake stori evid anyth video',
 'sport bar owner ban nfl game show true american sport like speak rural america video',
 'latest pipelin leak underscor danger dakota access pipelin',
 'gop senat smack punchabl alt right nazi internet',
 'may brexit offer would hurt cost eu citizen eu parliament',
 'schumer call trump appoint offici overse puerto rico relief',
 'watch hilari ad call question health age clinton crime famili boss',
 'chang expect espn polit agenda despit huge subscrib declin breitbart'

In [21]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[4981, 374, 1927, 1682, 1493, 2564, 171, 4725, 1704, 4899, 1553, 142],
 [4341,
  1967,
  1434,
  77,
  2213,
  4326,
  3255,
  144,
  2478,
  2006,
  2718,
  4007,
  503,
  142],
 [1401, 2251, 1566, 1170, 4642, 2938, 2529, 3962, 2279, 1821, 619, 3036],
 [3402, 4712, 4008, 4167, 4381, 2598, 3592, 2777, 3837, 1942, 4778],
 [4340, 2529, 466, 2671, 4662, 2175, 107, 2515, 466],
 [2003, 2414, 3161, 4486, 3583, 1904, 1614, 2176, 2368, 501, 3335],
 [2381, 721, 1952, 1934, 4712, 1572, 2938, 1878, 593, 142],
 [2462,
  4266,
  3782,
  2170,
  2880,
  2541,
  1088,
  2198,
  2062,
  2462,
  161,
  292,
  4338,
  3873,
  142],
 [3596, 2616, 1099, 687, 2503, 4551, 3442, 2616],
 [2665, 2571, 564, 2005, 3702, 3803, 2500, 3043],
 [4749, 1256, 2357, 4567, 649, 2343, 3878, 117, 3878, 899],
 [1313, 3953, 1934, 2961, 4515, 4052, 382, 8, 4688],
 [3372, 2884, 1739, 3953, 3987, 4451, 355, 3227, 4919, 1905, 3728],
 [4354, 4184, 3713, 4807, 1820, 49, 3662, 1766, 1100, 4188],
 [1112, 2361, 1335, 2666, 1979, 238

In [ ]:
## corpus[1]= 'unbeliev obama attorney gener say charlott rioter peac protest home state north carolina video'
onehot_repr[1]

[4341, 1967, 1434, 77, 2213, 4326, 3255, 144, 2478, 2006, 2718, 4007, 503, 142]

# Embedding Representation

In [23]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[4981  374 1927 ...    0    0    0]
 [4341 1967 1434 ...    0    0    0]
 [1401 2251 1566 ...    0    0    0]
 ...
 [1641 3665 3691 ...    0    0    0]
 [1934 2322 2649 ...    0    0    0]
 [2982 2905 4112 ...    0    0    0]]


In [24]:
embedded_docs[1]

array([4341, 1967, 1434,   77, 2213, 4326, 3255,  144, 2478, 2006, 2718,
       4007,  503,  142,    0,    0,    0,    0,    0,    0])

In [25]:
## Creating model
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())



Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256501 (1001.96 KB)
Trainable params: 256501 (1001.96 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [26]:
len(embedded_docs),y.shape

(71537, (71537,))

In [28]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [29]:
X_final.shape,y_final.shape

((71537, 20), (71537,))

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)